# msInvader handoff configuration generator
# 
# Produces a standardized YAML config skeleton so a subsequent authorised
# adversary-simulation run (msInvader) can consume test-tenant tokens/credentials
# without re-entering tenant details. This writes a CONFIG TEMPLATE only; it does
# not itself perform any post-exploitation actions.

from __future__ import annotations

from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None

def build_msinvader_config(config, auth_method: str = "device_code_flow", token: str | None = None) -> dict[str, Any]:
    """Return an msInvader-style config dict for the declared test tenant."""

    target_upn = config.users[0].upn if config.users else ""
    doc: dict[str, Any] = {
        "# NOTE": (
            "Generated by M365 TDVE for authorised detection validation on a "
            "TEST tenant only. Review before use."
        ),
        "authentication": {
            "method": auth_method,
            "tenant": config.tenant,
            "client_id": config.client_id,
            "username": target_upn,
            # Secrets are intentionally left blank / env-driven.
            "token": token or "${MSINVADER_TOKEN}",
        },
        "graph": {"enabled": True},
        "ews": {"enabled": False},
        "modules": [
            {"technique": "read_mailbox", "enabled": False},
            {"technique": "enumerate_users", "enabled": False},
        ],
    }

    return doc

def write_msinvader_config(config, 
                           path: str | Path,
                           auth_method: str = "device_code_flow",
                           token: str | None = None) -> Path:
    if yaml is None:
        raise RuntimeError("pyyaml is required to write the msInvader config.")
    
    doc = build_msinvader_config(config, auth_method=auth_method, token=token)
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(yaml.safe_dump(doc, sort_keys=False), encoding="utf-8")

    return p
